---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allowed-psps
  namespace: kube-system
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['gce.privileged']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-psps
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allowed-psps
subjects:
- kind: ServiceAccount
  name: metadata-agent
  namespace: kube-system
