apiVersion: v1
kind: Namespace
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: mysql

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allowed-psps
  namespace: mysql
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['mysql']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allowed-psps
  namespace: mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allowed-psps
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: mysql
  namespace: mysql

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: mysql
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
