apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-pulsifer-ca
  namespace: bullseye
  labels:
    app.kubernetes.io/name: bullseye
    app.kubernetes.io/part-of: bullseye
spec:
  secretName: k8s-pulsifer-ca-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: k8s.pulsifer.ca
  dnsNames:
  - k8s.pulsifer.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - k8s.pulsifer.ca
    - http01:
        ingress: k8s-pulsifer-ca
      domains:
      - k8s.pulsifer.ca
